[package]
name = "sp3"
version = "1.1.1"
license = "MPL-2.0"
authors = ["Guillaume W. Bres <guillaume.bressaix@gmail.com>"]
description = "IGS SP3 file parser"
homepage = "https://github.com/rtk-rs"
repository = "https://github.com/rtk-rs/sp3"
documentation = "https://docs.rs/sp3/"
keywords = ["gnss", "timing", "gps", "geo"]
categories = ["science", "science::geo", "parsing"]
edition = "2021"
readme = "README.md"
exclude = [
    "data/*",
]

[features]
default = ["flate2"] # gzip files by default

# File Merging and other high level methods
qc = [
    "gnss-qc-traits",
]

# (Pre)Processing methods like data masking 
processing = [
    "qc",
    "gnss-qc-traits/processing",
]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docrs", "--generate-link-to-definition"]

[dependencies]
thiserror = "2"
hifitime = "4.0"
itertools = "0.14"
anise = { version = "0.5.3", optional = true }
gnss-rs = { version = "2.3.5", features = ["serde"] }
gnss-qc-traits = { version = "0.1.0", optional = true }
serde = { version = "1.0", optional = true, default-features = false, features = ["derive"] }
flate2 = { version = "1", optional = true, default-features = false, features = ["zlib"] }
