name: Release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    continue-on-error: true
    if: github.ref_type == 'tag'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Publish
        env:
          TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
        run: |
          cargo login $TOKEN
          cargo publish --allow-dirty
  
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: ['publish']
    steps:
    - name: Create Release
      id: create_release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      uses: actions/create-release@v1
      with:
        draft: true
        tag_name: ${{ github.ref_name }}
        release_name: ${{ github.ref_name }}

    - name: Download Artifact
      uses: actions/download-artifact@v4
      with: 
        name: sp3-${{ github.ref_name }}
    
    - name: Upload asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: sp3-${{ github.ref_name }}
        asset_name: sp3-${{ github.ref_name }}
        asset_content_type: application/gzip
